### ISSUE TITLE
LPVS Error log from #209 

### ISSUE THREAD

**Issue by tiokim** [Samsung/LPVS#210]
```
lpvs-lpvs-1     | 2023-09-12 05:38:42.208 ERROR 1 --- [  LPVS-ASYNC::2] com.lpvs.service.LPVSQueueService        : Can't authorize commentResults() com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 1069 path $.purl[2]
lpvs-lpvs-1     | com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 1069 path $.purl[2]
lpvs-lpvs-1     | 	at com.google.gson.Gson.fromJson(Gson.java:1241)
lpvs-lpvs-1     | 	at com.google.gson.Gson.fromJson(Gson.java:1137)
lpvs-lpvs-1     | 	at com.google.gson.Gson.fromJson(Gson.java:1047)
lpvs-lpvs-1     | 	at com.google.gson.Gson.fromJson(Gson.java:982)
lpvs-lpvs-1     | 	at com.lpvs.service.scanner.scanoss.LPVSScanossDetectService.checkLicenses(LPVSScanossDetectService.java:143)
lpvs-lpvs-1     | 	at com.lpvs.service.LPVSDetectService.runScan(LPVSDetectService.java:44)
lpvs-lpvs-1     | 	at com.lpvs.service.LPVSQueueService.processWebHook(LPVSQueueService.java:159)
lpvs-lpvs-1     | 	at com.lpvs.service.LPVSQueueService$$FastClassBySpringCGLIB$$42722be.invoke(<generated>)
lpvs-lpvs-1     | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
lpvs-lpvs-1     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
lpvs-lpvs-1     | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
lpvs-lpvs-1     | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
lpvs-lpvs-1     | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
lpvs-lpvs-1     | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
lpvs-lpvs-1     | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
lpvs-lpvs-1     | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
lpvs-lpvs-1     | 	at java.base/java.lang.Thread.run(Thread.java:829)
lpvs-lpvs-1     | Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 1069 path $.purl[2]
lpvs-lpvs-1     | 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
lpvs-lpvs-1     | 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:485)
lpvs-lpvs-1     | 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422)
lpvs-lpvs-1     | 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
lpvs-lpvs-1     | 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
lpvs-lpvs-1     | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
lpvs-lpvs-1     | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
lpvs-lpvs-1     | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
lpvs-lpvs-1     | 	at com.google.gson.Gson.fromJson(Gson.java:1227)
lpvs-lpvs-1     | 	... 16 more
```

**Comment by m-rudyk** [comment]
@tiokim, It is similar error with issue #208. After fix, need to ensure that this one is working correctly. If possible, please share PR to reproduce above issue.

**Comment by tiokim** [comment]
Okay. Let's close this issue now. I'll reopen this if we need to fix.

**Comment by tiokim** [comment]
Reopen this since it's not resolved.

**Comment by tiokim** [comment]
@m-rudyk I tested this on the commit `f902dbce95d3ab89da27f5c56f62a912b16b90b9` with the PR #209 , and saw the same error on the lpvs container and no comment on GitHub. See my test PR [here](https://github.com/tiokim/LPVS/pull/100).

**Comment by m-rudyk** [comment]
> @m-rudyk I tested this on the commit `f902dbce95d3ab89da27f5c56f62a912b16b90b9` with the PR #209 , and saw the same error on the lpvs container and no comment on GitHub. See my test PR [here](https://github.com/tiokim/LPVS/pull/100).

kindly ask you to rerun (redeliver payload from that date) this PR, cause I can't reproduce that issue with similar error logs. 
Copy of PR is here: https://github.com/m-rudyk/LPVS/pull/5
https://github.com/m-rudyk/LPVS/pull/5#issuecomment-1731250549 => message left by LPVS.

**Comment by tiokim** [comment]
It works good. Sorry for my mistake. Thank you!
